In [1]:
import numpy as np
import cv2

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [1]:
size = 11

1.2. Створити нульовий масив заданого розміру

In [3]:
arr = np.zeros([size, size])

1.3 Надрукувати створений масив

In [4]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [5]:
for i in range(size):
	for j in range(size):
		if (i==j):
			arr[i][j] = 1
		elif (size-i-1==j):
			arr[i][j] = 1

1.5 Вивести створений масив 

#

In [6]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

Приклад зображення градієнту
<img src="./Data/Intro to Numpy/grad_example.jpg" height="200" width="200">

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [7]:
size = 255
horizontal_gradient1 = np.zeros([size,size])

2.2 Визначити розміри масиву

In [8]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

In [9]:
for i in range(h):
    for j in range(w):
        horizontal_gradient1[i][j] = j

2.4 Записати зображення засабами OpenCV

In [10]:
cv2.imwrite('Data/Intro to Numpy/resualt1.jpg', horizontal_gradient1)

True

**Отриманий нами результат**
<img src="./Data/Intro to Numpy/resualt1.jpg" height="200" width="200">

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [11]:
horizontal_gradient2 = np.zeros([size,size])

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(h):
    for j in range(w):
        horizontal_gradient2[i][j] = w - j - 1 
        
cv2.imwrite('Data/Intro to Numpy/resualt2.jpg', horizontal_gradient2)

True

**Отриманий нами результат**
<img src="./Data/Intro to Numpy/resualt2.jpg" height="200" width="200">

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [12]:
vertical_gradient1 = np.zeros([size,size])

2.7 Визначити розміри масиву

In [13]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]

2.8 Поелементно змінити яскравості кожного пікселя

In [14]:
for i in range(h):
    for j in range(w):
        vertical_gradient1[i][j] = i

2.9 Записати зображення засабами OpenCV

In [15]:
cv2.imwrite('Data/Intro to Numpy/resualt3.jpg', vertical_gradient1)

True

**Отриманий нами результат**
<img src="./Data/Intro to Numpy/resualt3.jpg" height="200" width="200">

2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [16]:
vertical_gradient2 = np.zeros([size,size])

w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]

for i in range(h):
    for j in range(w):
        vertical_gradient2[i][j] = h - i - 1
        
cv2.imwrite('Data/Intro to Numpy/resualt4.jpg', vertical_gradient2)


True

**Отриманий нами результат**
<img src="./Data/Intro to Numpy/resualt4.jpg" height="200" width="200">